// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using ToDo2.Controllers.Data;

namespace ToDo2.Migrations
{
    [DbContext(typeof(ToDoListDbContext))]
    partial class ToDoListDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToDo2.Models.ListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ListItemsId");

                    b.Property<string>("Name");

                    b.Property<string>("Task");

                    b.Property<int?>("ToDosId");

                    b.HasKey("Id");

                    b.HasIndex("ListItemsId");

                    b.HasIndex("ToDosId");

                    b.ToTable("ListItems");
                });

            modelBuilder.Entity("ToDo2.Models.ToDos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ToDos");
                });

            modelBuilder.Entity("ToDo2.Models.ListItem", b =>
                {
                    b.HasOne("ToDo2.Models.ListItem", "ListItems")
                        .WithMany()
                        .HasForeignKey("ListItemsId");

                    b.HasOne("ToDo2.Models.ToDos", "ToDos")
                        .WithMany("ListItems")
                        .HasForeignKey("ToDosId");
                });
#pragma warning restore 612, 618
        }
    }
}
